### ISSUE TITLE
佬，希望[提示]支持 富文本编辑 

### ISSUE THREAD

**Issue by the-best-richer** [nuanxinqing123/QLToolsV2#2]
平时个人使用中，编辑变量-提示内容 更像是用来给活动的介绍和说明，希望支持富文本编辑和渲染，这样可以高亮和加粗，放链接或者图片之类的

**Comment by nuanxinqing123** [comment]
> 平时个人使用中，编辑变量-提示内容 更像是用来给活动的介绍和说明，希望支持富文本编辑和渲染，这样可以高亮和加粗，放链接或者图片之类的

好的。
